# A string is simply an ordered collection of symbols selected from some
# alphabet and formed into a word; the length of a string is the number of
# symbols that it contains.

# An example of a length 21 DNA string (whose alphabet contains the symbols
# 'A', 'C', 'G', and 'T') is "ATGCTTCAGAAAGGTCTTACG."

# Given: A DNA string s of length at most 1000 nt.

# Return: Four integers (separated by spaces) counting the respective number
# of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

a_count = 0
c_count = 0
g_count = 0
t_count = 0

s = "GTGGGGAGGAGTGGGTGCACGAGGGCCCGACGAGCTAATGCCGGATACCATGGCTGCCTAGCACACCCTAGTCGATAACGAGTGGGCAGGGCTCAAGCAAATCACCCTCTATGTAGATGCAAGTGTCGGTGTTGCAAGGACTCCCATCGCGAGAGATCAGAGAGACGTTTCCACAATCTGGCAGACACTCGGCCGGAGCTCCGCGCACTACCATGTCCCAGGGTATCGGTCGCTGCTACGTCCCTCAGAACGGATGCACATAAGTAGCGATCGTGTTAGCAACATCAGAGTAATCGCGGCCAAATAGACAAAAATGTCCGAAACCAGTCACTCCTGCGTCTACAATATGAGTCCTCGCCCAGCTATGGGGTGTGTTACACAAAACCGCACTTTGGCCCCTCGTGAAAGGACCTCGACTTCGGATATCTAGACTTATAGTCGCAATGCGTAGTGCCCTTTCTGGGGAGATACGAGCTCTAATTGGGACTACTCGTTGCCCTTGGCTTAGCGAAATAGTCATTCTAACCTCCTACGTACTGGGCTGAGTTGGCTATACCATGTCCCTCGTCGGCACAGAGGAGCTTAAGCCCGTAACCAGTTACTTGCATCTACAACTACATAAAACCAGGGGGTAGTCAATGCCTATACCCGTCCGTGTGACGTGCTCTGAGCGCCGAATGCAACGTATCCATCCAAGCAAAGTTCGGTACAAAGTGTCAACTAGCGATTAGCCCACAGTATAATGCAGATGTGCCACCTGGCACTTAATAGGGCGACAAGAAATTAAAGCGAGATTCGTAACAAGCTGCGTTCCGTAATATTTACCCATTAT"

for char in s:
    if char == "A":
        a_count += 1
    if char == "C":
        c_count += 1
    if char == "G":
        g_count += 1
    if char == "T":
        t_count += 1
    
print(a_count, c_count, g_count, t_count)


